[package]
name = "ion-binary-rs"
version = "0.2.1"
authors = ["David Bonet <webbonet@gmail.com>"]
edition = "2018"
description="Pure Rust binary parser for Amazon's Ion. It helps to communicate with products lik QLDB."
license = "Apache-2.0/MIT"
readme = "README.md"
keywords = ["ion", "binary", "network", "protocol", "amazon"]
categories = ["network-programming", "network", "ion", "amazon"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
bytes = "0.5.6"
chrono = "0.4.15"
log = "0.4.11"
env_logger = "0.7.1"
bigdecimal = "0.2.0"
num-bigint = "0.3.0"
use = "0.0.0"
num-traits = "0.2.12"
