name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: rust-tarpaulin
      uses: actions-rs/tarpaulin@v0.1.0
      with:
        # Extra command line arguments passed to cargo-tarpaulin
        args: "-o Xml"  
    - name: Code coverage upload
      uses: codecov/codecov-action@v1.0.13
      with:
        file: "target/tarpaulin/coverage.json"
